### ISSUE TITLE
Test development branch

### ISSUE THREAD

**Issue by saleemhamo** [saleemhamo/traffic-light-system#54]

**Comment by saleemhamo** [comment]
- Traffic light sync 
- Checking System 
	- Button 
	- Ultrasonic 1
	- Ultrasonic 2
	- Camera?
- Warning System
	- LEDs
	- Buzzer

**Comment by AlexandruRO45** [comment]
> * Traffic light sync - PASSED
> * Checking System
>   
>   * Button - PASSED
>   * Ultrasonic 1 - PASSED WITH CONDITION (required fix of calibration of motion value distance)
>   * Ultrasonic 2 -  PASSED WITH CONDITION (required fix of calibration of motion value distance)
>   * Camera? - FAILED (Not implemented correctly)
> * Warning System
>   
>   * LEDs - PASSED
>   * Buzzer - PASSED
